name: surf
channels:
  - conda-forge
  - defaults
dependencies:
  - spacy
  - tqdm
  - ipython
  - jupyter
  - nb_conda
  - nb_conda_kernels
  - notebook
  - numpy
  - pip
  - python=3.6.6
  - requests
  - scikit-learn
  - scipy
  - django==1.11.*
  - jsonschema==2.6.0
  - pip:
    - autopep8==1.3.5
    - jupyter-contrib-core==0.3.3
    - jupyter-nbextensions-configurator==0.4.0
    - pycodestyle==2.4.0
    - youtube-dl==2018.8.22
    - pysoundfile==0.9.0
    - https://github.com/explosion/spacy-models/releases/download/nl_core_news_sm-2.0.0/nl_core_news_sm-2.0.0.tar.gz
    - git+https://github.com/fako/django-json-field.git
