name: surf-p27
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - pip
  - python=2.7.*
  - pip:
    - git+https://github.com/seecr/cqlparser.git
    - https://github.com/explosion/spacy-models/releases/download/nl_core_news_sm-2.0.0/nl_core_news_sm-2.0.0.tar.gz